version: "3"
services:
    web-app:
        build: .
        command: sh -c 'npm install; npm start'
        ports:
            - '3000:3000'
        volumes:
            - /home/fernanda/Escritorio/starwars-redis/api:/api
        depends_on:
            - "db-redis"
            
    db-redis:
        container_name: 'starwars-api'
        image: redis
        ports:
            - "6379:6379"